---
# bitwarden.yml

- name: Find download url for the latest version of Bitwarden cli
  shell: curl -sL https://api.github.com/repos/bitwarden/cli/releases |jq -r '.[0].assets[] | select(.browser_download_url | contains("linux")).browser_download_url'
  args:
    executable: /bin/bash
  register: bitwarden_url

- name: Download and extract the Bitwarden from its archive
  unarchive:
    src: "{{ bitwarden_url.stdout }}"
    dest: /usr/local/bin
    remote_src: yes
    mode: 0755
    owner: root
    creates: /usr/local/bin/bw
