---

- name: Create ~/.gitconfig
  template:
    src: gitconfig.j2
    dest: '{{ my_user_home }}/.gitconfig'
    owner: '{{ my_user }}'
    group: '{{ my_user }}'

- name: Create ~/.vimrc
  template:
    src: vimrc.j2
    dest: '{{ my_user_home }}/.vimrc'
    owner: '{{ my_user }}'
    group: '{{ my_user }}'

- name: Create ~/.bashrc
  template:
    src: bashrc.j2
    dest: '{{ my_user_home }}/.bashrc'
    owner: '{{ my_user }}'
    group: '{{ my_user }}'

- name: Create ~/.bash_profile
  template:
    src: bash_profile.j2
    dest: '{{ my_user_home }}/.bash_profile'
    owner: '{{ my_user }}'
    group: '{{ my_user }}'

