---
# tasks file for workstation
- include_tasks: users.yml

- include_tasks: kryptco.yml

- include_tasks: packages.yml

- include_tasks: dotfiles.yml

- include_tasks: vim8.yml

- include_tasks: awscli.yml
  when: install_aws == true

- include_tasks: gcp.yml
  when: install_gcp == true

- include_tasks: terraform.yml
  when: install_terraform == true
