---
# packages.yml

- name: Install EPEL repository
  yum:
    name: epel-release
    state: latest
    disable_gpg_check: true

- name: Install my packages
  yum:
    name: '{{ packages }}'
    state: latest
    disable_gpg_check: true
