---

- name: Add system user
  user:
    name: '{{ my_user }}'
    home: '{{ my_user_home }}'
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa

- name: Grant user passwordless sudo access
  lineinfile:
    create: yes
    line: '{{ my_user }}        ALL=(ALL)       NOPASSWD: ALL'
    path: '/etc/sudoers.d/00_{{ my_user }}'
    owner: root
    group: root
    mode: 0440

